// Code generated by protoc-gen-go. DO NOT EDIT.
// source: noderpc.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUsernameRequest) Reset()         { *m = SetUsernameRequest{} }
func (m *SetUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*SetUsernameRequest) ProtoMessage()    {}
func (*SetUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{0}
}
func (m *SetUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUsernameRequest.Unmarshal(m, b)
}
func (m *SetUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUsernameRequest.Marshal(b, m, deterministic)
}
func (dst *SetUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUsernameRequest.Merge(dst, src)
}
func (m *SetUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_SetUsernameRequest.Size(m)
}
func (m *SetUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUsernameRequest proto.InternalMessageInfo

func (m *SetUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type SetUsernameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUsernameResponse) Reset()         { *m = SetUsernameResponse{} }
func (m *SetUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*SetUsernameResponse) ProtoMessage()    {}
func (*SetUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{1}
}
func (m *SetUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUsernameResponse.Unmarshal(m, b)
}
func (m *SetUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUsernameResponse.Marshal(b, m, deterministic)
}
func (dst *SetUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUsernameResponse.Merge(dst, src)
}
func (m *SetUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_SetUsernameResponse.Size(m)
}
func (m *SetUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUsernameResponse proto.InternalMessageInfo

type InitRepoRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRepoRequest) Reset()         { *m = InitRepoRequest{} }
func (m *InitRepoRequest) String() string { return proto.CompactTextString(m) }
func (*InitRepoRequest) ProtoMessage()    {}
func (*InitRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{2}
}
func (m *InitRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRepoRequest.Unmarshal(m, b)
}
func (m *InitRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRepoRequest.Marshal(b, m, deterministic)
}
func (dst *InitRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRepoRequest.Merge(dst, src)
}
func (m *InitRepoRequest) XXX_Size() int {
	return xxx_messageInfo_InitRepoRequest.Size(m)
}
func (m *InitRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRepoRequest proto.InternalMessageInfo

func (m *InitRepoRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *InitRepoRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type InitRepoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRepoResponse) Reset()         { *m = InitRepoResponse{} }
func (m *InitRepoResponse) String() string { return proto.CompactTextString(m) }
func (*InitRepoResponse) ProtoMessage()    {}
func (*InitRepoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{3}
}
func (m *InitRepoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRepoResponse.Unmarshal(m, b)
}
func (m *InitRepoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRepoResponse.Marshal(b, m, deterministic)
}
func (dst *InitRepoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRepoResponse.Merge(dst, src)
}
func (m *InitRepoResponse) XXX_Size() int {
	return xxx_messageInfo_InitRepoResponse.Size(m)
}
func (m *InitRepoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRepoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitRepoResponse proto.InternalMessageInfo

type GetObjectRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	ObjectID             []byte   `protobuf:"bytes,2,opt,name=objectID,proto3" json:"objectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{4}
}
func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (dst *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(dst, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetObjectRequest) GetObjectID() []byte {
	if m != nil {
		return m.ObjectID
	}
	return nil
}

type GetObjectResponsePacket struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponsePacket) Reset()         { *m = GetObjectResponsePacket{} }
func (m *GetObjectResponsePacket) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponsePacket) ProtoMessage()    {}
func (*GetObjectResponsePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{5}
}
func (m *GetObjectResponsePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponsePacket.Unmarshal(m, b)
}
func (m *GetObjectResponsePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponsePacket.Marshal(b, m, deterministic)
}
func (dst *GetObjectResponsePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponsePacket.Merge(dst, src)
}
func (m *GetObjectResponsePacket) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponsePacket.Size(m)
}
func (m *GetObjectResponsePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponsePacket.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponsePacket proto.InternalMessageInfo

func (m *GetObjectResponsePacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RegisterRepoIDRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRepoIDRequest) Reset()         { *m = RegisterRepoIDRequest{} }
func (m *RegisterRepoIDRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRepoIDRequest) ProtoMessage()    {}
func (*RegisterRepoIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{6}
}
func (m *RegisterRepoIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRepoIDRequest.Unmarshal(m, b)
}
func (m *RegisterRepoIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRepoIDRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRepoIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRepoIDRequest.Merge(dst, src)
}
func (m *RegisterRepoIDRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRepoIDRequest.Size(m)
}
func (m *RegisterRepoIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRepoIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRepoIDRequest proto.InternalMessageInfo

func (m *RegisterRepoIDRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

type RegisterRepoIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRepoIDResponse) Reset()         { *m = RegisterRepoIDResponse{} }
func (m *RegisterRepoIDResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterRepoIDResponse) ProtoMessage()    {}
func (*RegisterRepoIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{7}
}
func (m *RegisterRepoIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRepoIDResponse.Unmarshal(m, b)
}
func (m *RegisterRepoIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRepoIDResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterRepoIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRepoIDResponse.Merge(dst, src)
}
func (m *RegisterRepoIDResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterRepoIDResponse.Size(m)
}
func (m *RegisterRepoIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRepoIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRepoIDResponse proto.InternalMessageInfo

type TrackLocalRepoRequest struct {
	RepoPath             string   `protobuf:"bytes,1,opt,name=repoPath,proto3" json:"repoPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackLocalRepoRequest) Reset()         { *m = TrackLocalRepoRequest{} }
func (m *TrackLocalRepoRequest) String() string { return proto.CompactTextString(m) }
func (*TrackLocalRepoRequest) ProtoMessage()    {}
func (*TrackLocalRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{8}
}
func (m *TrackLocalRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackLocalRepoRequest.Unmarshal(m, b)
}
func (m *TrackLocalRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackLocalRepoRequest.Marshal(b, m, deterministic)
}
func (dst *TrackLocalRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackLocalRepoRequest.Merge(dst, src)
}
func (m *TrackLocalRepoRequest) XXX_Size() int {
	return xxx_messageInfo_TrackLocalRepoRequest.Size(m)
}
func (m *TrackLocalRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackLocalRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrackLocalRepoRequest proto.InternalMessageInfo

func (m *TrackLocalRepoRequest) GetRepoPath() string {
	if m != nil {
		return m.RepoPath
	}
	return ""
}

type TrackLocalRepoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackLocalRepoResponse) Reset()         { *m = TrackLocalRepoResponse{} }
func (m *TrackLocalRepoResponse) String() string { return proto.CompactTextString(m) }
func (*TrackLocalRepoResponse) ProtoMessage()    {}
func (*TrackLocalRepoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{9}
}
func (m *TrackLocalRepoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackLocalRepoResponse.Unmarshal(m, b)
}
func (m *TrackLocalRepoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackLocalRepoResponse.Marshal(b, m, deterministic)
}
func (dst *TrackLocalRepoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackLocalRepoResponse.Merge(dst, src)
}
func (m *TrackLocalRepoResponse) XXX_Size() int {
	return xxx_messageInfo_TrackLocalRepoResponse.Size(m)
}
func (m *TrackLocalRepoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackLocalRepoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrackLocalRepoResponse proto.InternalMessageInfo

type GetLocalReposRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLocalReposRequest) Reset()         { *m = GetLocalReposRequest{} }
func (m *GetLocalReposRequest) String() string { return proto.CompactTextString(m) }
func (*GetLocalReposRequest) ProtoMessage()    {}
func (*GetLocalReposRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{10}
}
func (m *GetLocalReposRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocalReposRequest.Unmarshal(m, b)
}
func (m *GetLocalReposRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocalReposRequest.Marshal(b, m, deterministic)
}
func (dst *GetLocalReposRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocalReposRequest.Merge(dst, src)
}
func (m *GetLocalReposRequest) XXX_Size() int {
	return xxx_messageInfo_GetLocalReposRequest.Size(m)
}
func (m *GetLocalReposRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocalReposRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocalReposRequest proto.InternalMessageInfo

type GetLocalReposResponsePacket struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLocalReposResponsePacket) Reset()         { *m = GetLocalReposResponsePacket{} }
func (m *GetLocalReposResponsePacket) String() string { return proto.CompactTextString(m) }
func (*GetLocalReposResponsePacket) ProtoMessage()    {}
func (*GetLocalReposResponsePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{11}
}
func (m *GetLocalReposResponsePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocalReposResponsePacket.Unmarshal(m, b)
}
func (m *GetLocalReposResponsePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocalReposResponsePacket.Marshal(b, m, deterministic)
}
func (dst *GetLocalReposResponsePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocalReposResponsePacket.Merge(dst, src)
}
func (m *GetLocalReposResponsePacket) XXX_Size() int {
	return xxx_messageInfo_GetLocalReposResponsePacket.Size(m)
}
func (m *GetLocalReposResponsePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocalReposResponsePacket.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocalReposResponsePacket proto.InternalMessageInfo

func (m *GetLocalReposResponsePacket) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetLocalReposResponsePacket) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SetReplicationPolicyRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	ShouldReplicate      bool     `protobuf:"varint,2,opt,name=shouldReplicate,proto3" json:"shouldReplicate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReplicationPolicyRequest) Reset()         { *m = SetReplicationPolicyRequest{} }
func (m *SetReplicationPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*SetReplicationPolicyRequest) ProtoMessage()    {}
func (*SetReplicationPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{12}
}
func (m *SetReplicationPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReplicationPolicyRequest.Unmarshal(m, b)
}
func (m *SetReplicationPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReplicationPolicyRequest.Marshal(b, m, deterministic)
}
func (dst *SetReplicationPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReplicationPolicyRequest.Merge(dst, src)
}
func (m *SetReplicationPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_SetReplicationPolicyRequest.Size(m)
}
func (m *SetReplicationPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReplicationPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetReplicationPolicyRequest proto.InternalMessageInfo

func (m *SetReplicationPolicyRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *SetReplicationPolicyRequest) GetShouldReplicate() bool {
	if m != nil {
		return m.ShouldReplicate
	}
	return false
}

type SetReplicationPolicyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReplicationPolicyResponse) Reset()         { *m = SetReplicationPolicyResponse{} }
func (m *SetReplicationPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*SetReplicationPolicyResponse) ProtoMessage()    {}
func (*SetReplicationPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{13}
}
func (m *SetReplicationPolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReplicationPolicyResponse.Unmarshal(m, b)
}
func (m *SetReplicationPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReplicationPolicyResponse.Marshal(b, m, deterministic)
}
func (dst *SetReplicationPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReplicationPolicyResponse.Merge(dst, src)
}
func (m *SetReplicationPolicyResponse) XXX_Size() int {
	return xxx_messageInfo_SetReplicationPolicyResponse.Size(m)
}
func (m *SetReplicationPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReplicationPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetReplicationPolicyResponse proto.InternalMessageInfo

type AnnounceRepoContentRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceRepoContentRequest) Reset()         { *m = AnnounceRepoContentRequest{} }
func (m *AnnounceRepoContentRequest) String() string { return proto.CompactTextString(m) }
func (*AnnounceRepoContentRequest) ProtoMessage()    {}
func (*AnnounceRepoContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{14}
}
func (m *AnnounceRepoContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceRepoContentRequest.Unmarshal(m, b)
}
func (m *AnnounceRepoContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceRepoContentRequest.Marshal(b, m, deterministic)
}
func (dst *AnnounceRepoContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceRepoContentRequest.Merge(dst, src)
}
func (m *AnnounceRepoContentRequest) XXX_Size() int {
	return xxx_messageInfo_AnnounceRepoContentRequest.Size(m)
}
func (m *AnnounceRepoContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceRepoContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceRepoContentRequest proto.InternalMessageInfo

func (m *AnnounceRepoContentRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

type AnnounceRepoContentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceRepoContentResponse) Reset()         { *m = AnnounceRepoContentResponse{} }
func (m *AnnounceRepoContentResponse) String() string { return proto.CompactTextString(m) }
func (*AnnounceRepoContentResponse) ProtoMessage()    {}
func (*AnnounceRepoContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{15}
}
func (m *AnnounceRepoContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceRepoContentResponse.Unmarshal(m, b)
}
func (m *AnnounceRepoContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceRepoContentResponse.Marshal(b, m, deterministic)
}
func (dst *AnnounceRepoContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceRepoContentResponse.Merge(dst, src)
}
func (m *AnnounceRepoContentResponse) XXX_Size() int {
	return xxx_messageInfo_AnnounceRepoContentResponse.Size(m)
}
func (m *AnnounceRepoContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceRepoContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceRepoContentResponse proto.InternalMessageInfo

type Ref struct {
	RefName              string   `protobuf:"bytes,1,opt,name=refName,proto3" json:"refName,omitempty"`
	CommitHash           string   `protobuf:"bytes,2,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref) Reset()         { *m = Ref{} }
func (m *Ref) String() string { return proto.CompactTextString(m) }
func (*Ref) ProtoMessage()    {}
func (*Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{16}
}
func (m *Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref.Unmarshal(m, b)
}
func (m *Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref.Marshal(b, m, deterministic)
}
func (dst *Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref.Merge(dst, src)
}
func (m *Ref) XXX_Size() int {
	return xxx_messageInfo_Ref.Size(m)
}
func (m *Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref.DiscardUnknown(m)
}

var xxx_messageInfo_Ref proto.InternalMessageInfo

func (m *Ref) GetRefName() string {
	if m != nil {
		return m.RefName
	}
	return ""
}

func (m *Ref) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

type GetRefsRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	PageSize             uint64   `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Page                 uint64   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRefsRequest) Reset()         { *m = GetRefsRequest{} }
func (m *GetRefsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRefsRequest) ProtoMessage()    {}
func (*GetRefsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{17}
}
func (m *GetRefsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefsRequest.Unmarshal(m, b)
}
func (m *GetRefsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefsRequest.Marshal(b, m, deterministic)
}
func (dst *GetRefsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefsRequest.Merge(dst, src)
}
func (m *GetRefsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRefsRequest.Size(m)
}
func (m *GetRefsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefsRequest proto.InternalMessageInfo

func (m *GetRefsRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetRefsRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetRefsRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetRefsResponse struct {
	Total                uint64   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Refs                 []*Ref   `protobuf:"bytes,2,rep,name=refs,proto3" json:"refs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRefsResponse) Reset()         { *m = GetRefsResponse{} }
func (m *GetRefsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRefsResponse) ProtoMessage()    {}
func (*GetRefsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{18}
}
func (m *GetRefsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefsResponse.Unmarshal(m, b)
}
func (m *GetRefsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefsResponse.Marshal(b, m, deterministic)
}
func (dst *GetRefsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefsResponse.Merge(dst, src)
}
func (m *GetRefsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRefsResponse.Size(m)
}
func (m *GetRefsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefsResponse proto.InternalMessageInfo

func (m *GetRefsResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetRefsResponse) GetRefs() []*Ref {
	if m != nil {
		return m.Refs
	}
	return nil
}

type UpdateRefRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	RefName              string   `protobuf:"bytes,2,opt,name=refName,proto3" json:"refName,omitempty"`
	CommitHash           string   `protobuf:"bytes,3,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRefRequest) Reset()         { *m = UpdateRefRequest{} }
func (m *UpdateRefRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRefRequest) ProtoMessage()    {}
func (*UpdateRefRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{19}
}
func (m *UpdateRefRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRefRequest.Unmarshal(m, b)
}
func (m *UpdateRefRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRefRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRefRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRefRequest.Merge(dst, src)
}
func (m *UpdateRefRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRefRequest.Size(m)
}
func (m *UpdateRefRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRefRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRefRequest proto.InternalMessageInfo

func (m *UpdateRefRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *UpdateRefRequest) GetRefName() string {
	if m != nil {
		return m.RefName
	}
	return ""
}

func (m *UpdateRefRequest) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

type UpdateRefResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRefResponse) Reset()         { *m = UpdateRefResponse{} }
func (m *UpdateRefResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRefResponse) ProtoMessage()    {}
func (*UpdateRefResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{20}
}
func (m *UpdateRefResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRefResponse.Unmarshal(m, b)
}
func (m *UpdateRefResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRefResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateRefResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRefResponse.Merge(dst, src)
}
func (m *UpdateRefResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRefResponse.Size(m)
}
func (m *UpdateRefResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRefResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRefResponse proto.InternalMessageInfo

type GetRepoUsersRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	Type                 uint64   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	PageSize             uint64   `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Page                 uint64   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepoUsersRequest) Reset()         { *m = GetRepoUsersRequest{} }
func (m *GetRepoUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetRepoUsersRequest) ProtoMessage()    {}
func (*GetRepoUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{21}
}
func (m *GetRepoUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepoUsersRequest.Unmarshal(m, b)
}
func (m *GetRepoUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepoUsersRequest.Marshal(b, m, deterministic)
}
func (dst *GetRepoUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepoUsersRequest.Merge(dst, src)
}
func (m *GetRepoUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetRepoUsersRequest.Size(m)
}
func (m *GetRepoUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepoUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepoUsersRequest proto.InternalMessageInfo

func (m *GetRepoUsersRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetRepoUsersRequest) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetRepoUsersRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetRepoUsersRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetRepoUsersResponse struct {
	Total                uint64   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Users                []string `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepoUsersResponse) Reset()         { *m = GetRepoUsersResponse{} }
func (m *GetRepoUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetRepoUsersResponse) ProtoMessage()    {}
func (*GetRepoUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{22}
}
func (m *GetRepoUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepoUsersResponse.Unmarshal(m, b)
}
func (m *GetRepoUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepoUsersResponse.Marshal(b, m, deterministic)
}
func (dst *GetRepoUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepoUsersResponse.Merge(dst, src)
}
func (m *GetRepoUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetRepoUsersResponse.Size(m)
}
func (m *GetRepoUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepoUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepoUsersResponse proto.InternalMessageInfo

func (m *GetRepoUsersResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetRepoUsersResponse) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

type ReplicationRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationRequest) Reset()         { *m = ReplicationRequest{} }
func (m *ReplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicationRequest) ProtoMessage()    {}
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{23}
}
func (m *ReplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationRequest.Unmarshal(m, b)
}
func (m *ReplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationRequest.Marshal(b, m, deterministic)
}
func (dst *ReplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationRequest.Merge(dst, src)
}
func (m *ReplicationRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicationRequest.Size(m)
}
func (m *ReplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationRequest proto.InternalMessageInfo

func (m *ReplicationRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

type ReplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationResponse) Reset()         { *m = ReplicationResponse{} }
func (m *ReplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicationResponse) ProtoMessage()    {}
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{24}
}
func (m *ReplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationResponse.Unmarshal(m, b)
}
func (m *ReplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationResponse.Marshal(b, m, deterministic)
}
func (dst *ReplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationResponse.Merge(dst, src)
}
func (m *ReplicationResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicationResponse.Size(m)
}
func (m *ReplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationResponse proto.InternalMessageInfo

type GetRepoHistoryRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	Page                 uint64   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepoHistoryRequest) Reset()         { *m = GetRepoHistoryRequest{} }
func (m *GetRepoHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetRepoHistoryRequest) ProtoMessage()    {}
func (*GetRepoHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{25}
}
func (m *GetRepoHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepoHistoryRequest.Unmarshal(m, b)
}
func (m *GetRepoHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepoHistoryRequest.Marshal(b, m, deterministic)
}
func (dst *GetRepoHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepoHistoryRequest.Merge(dst, src)
}
func (m *GetRepoHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetRepoHistoryRequest.Size(m)
}
func (m *GetRepoHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepoHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepoHistoryRequest proto.InternalMessageInfo

func (m *GetRepoHistoryRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetRepoHistoryRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type Commit struct {
	CommitHash           string   `protobuf:"bytes,1,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{26}
}
func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (dst *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(dst, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

func (m *Commit) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Commit) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Commit) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetRepoHistoryResponse struct {
	Commits              []*Commit `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRepoHistoryResponse) Reset()         { *m = GetRepoHistoryResponse{} }
func (m *GetRepoHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetRepoHistoryResponse) ProtoMessage()    {}
func (*GetRepoHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{27}
}
func (m *GetRepoHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepoHistoryResponse.Unmarshal(m, b)
}
func (m *GetRepoHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepoHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *GetRepoHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepoHistoryResponse.Merge(dst, src)
}
func (m *GetRepoHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetRepoHistoryResponse.Size(m)
}
func (m *GetRepoHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepoHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepoHistoryResponse proto.InternalMessageInfo

func (m *GetRepoHistoryResponse) GetCommits() []*Commit {
	if m != nil {
		return m.Commits
	}
	return nil
}

type GetRepoFilesRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepoFilesRequest) Reset()         { *m = GetRepoFilesRequest{} }
func (m *GetRepoFilesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRepoFilesRequest) ProtoMessage()    {}
func (*GetRepoFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{28}
}
func (m *GetRepoFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepoFilesRequest.Unmarshal(m, b)
}
func (m *GetRepoFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepoFilesRequest.Marshal(b, m, deterministic)
}
func (dst *GetRepoFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepoFilesRequest.Merge(dst, src)
}
func (m *GetRepoFilesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRepoFilesRequest.Size(m)
}
func (m *GetRepoFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepoFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepoFilesRequest proto.InternalMessageInfo

func (m *GetRepoFilesRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetRepoFilesRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Mode                 uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Size                 uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	UnstagedStatus       string   `protobuf:"bytes,5,opt,name=unstagedStatus,proto3" json:"unstagedStatus,omitempty"`
	StagedStatus         string   `protobuf:"bytes,6,opt,name=stagedStatus,proto3" json:"stagedStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{29}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *File) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *File) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetUnstagedStatus() string {
	if m != nil {
		return m.UnstagedStatus
	}
	return ""
}

func (m *File) GetStagedStatus() string {
	if m != nil {
		return m.StagedStatus
	}
	return ""
}

type GetRepoFilesResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRepoFilesResponse) Reset()         { *m = GetRepoFilesResponse{} }
func (m *GetRepoFilesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRepoFilesResponse) ProtoMessage()    {}
func (*GetRepoFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_8199278bb2b521db, []int{30}
}
func (m *GetRepoFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRepoFilesResponse.Unmarshal(m, b)
}
func (m *GetRepoFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRepoFilesResponse.Marshal(b, m, deterministic)
}
func (dst *GetRepoFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRepoFilesResponse.Merge(dst, src)
}
func (m *GetRepoFilesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRepoFilesResponse.Size(m)
}
func (m *GetRepoFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRepoFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRepoFilesResponse proto.InternalMessageInfo

func (m *GetRepoFilesResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*SetUsernameRequest)(nil), "noderpc.SetUsernameRequest")
	proto.RegisterType((*SetUsernameResponse)(nil), "noderpc.SetUsernameResponse")
	proto.RegisterType((*InitRepoRequest)(nil), "noderpc.InitRepoRequest")
	proto.RegisterType((*InitRepoResponse)(nil), "noderpc.InitRepoResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "noderpc.GetObjectRequest")
	proto.RegisterType((*GetObjectResponsePacket)(nil), "noderpc.GetObjectResponsePacket")
	proto.RegisterType((*RegisterRepoIDRequest)(nil), "noderpc.RegisterRepoIDRequest")
	proto.RegisterType((*RegisterRepoIDResponse)(nil), "noderpc.RegisterRepoIDResponse")
	proto.RegisterType((*TrackLocalRepoRequest)(nil), "noderpc.TrackLocalRepoRequest")
	proto.RegisterType((*TrackLocalRepoResponse)(nil), "noderpc.TrackLocalRepoResponse")
	proto.RegisterType((*GetLocalReposRequest)(nil), "noderpc.GetLocalReposRequest")
	proto.RegisterType((*GetLocalReposResponsePacket)(nil), "noderpc.GetLocalReposResponsePacket")
	proto.RegisterType((*SetReplicationPolicyRequest)(nil), "noderpc.SetReplicationPolicyRequest")
	proto.RegisterType((*SetReplicationPolicyResponse)(nil), "noderpc.SetReplicationPolicyResponse")
	proto.RegisterType((*AnnounceRepoContentRequest)(nil), "noderpc.AnnounceRepoContentRequest")
	proto.RegisterType((*AnnounceRepoContentResponse)(nil), "noderpc.AnnounceRepoContentResponse")
	proto.RegisterType((*Ref)(nil), "noderpc.Ref")
	proto.RegisterType((*GetRefsRequest)(nil), "noderpc.GetRefsRequest")
	proto.RegisterType((*GetRefsResponse)(nil), "noderpc.GetRefsResponse")
	proto.RegisterType((*UpdateRefRequest)(nil), "noderpc.UpdateRefRequest")
	proto.RegisterType((*UpdateRefResponse)(nil), "noderpc.UpdateRefResponse")
	proto.RegisterType((*GetRepoUsersRequest)(nil), "noderpc.GetRepoUsersRequest")
	proto.RegisterType((*GetRepoUsersResponse)(nil), "noderpc.GetRepoUsersResponse")
	proto.RegisterType((*ReplicationRequest)(nil), "noderpc.ReplicationRequest")
	proto.RegisterType((*ReplicationResponse)(nil), "noderpc.ReplicationResponse")
	proto.RegisterType((*GetRepoHistoryRequest)(nil), "noderpc.GetRepoHistoryRequest")
	proto.RegisterType((*Commit)(nil), "noderpc.Commit")
	proto.RegisterType((*GetRepoHistoryResponse)(nil), "noderpc.GetRepoHistoryResponse")
	proto.RegisterType((*GetRepoFilesRequest)(nil), "noderpc.GetRepoFilesRequest")
	proto.RegisterType((*File)(nil), "noderpc.File")
	proto.RegisterType((*GetRepoFilesResponse)(nil), "noderpc.GetRepoFilesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeRPCClient is the client API for NodeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeRPCClient interface {
	SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...grpc.CallOption) (*SetUsernameResponse, error)
	InitRepo(ctx context.Context, in *InitRepoRequest, opts ...grpc.CallOption) (*InitRepoResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (NodeRPC_GetObjectClient, error)
	RegisterRepoID(ctx context.Context, in *RegisterRepoIDRequest, opts ...grpc.CallOption) (*RegisterRepoIDResponse, error)
	TrackLocalRepo(ctx context.Context, in *TrackLocalRepoRequest, opts ...grpc.CallOption) (*TrackLocalRepoResponse, error)
	GetLocalRepos(ctx context.Context, in *GetLocalReposRequest, opts ...grpc.CallOption) (NodeRPC_GetLocalReposClient, error)
	SetReplicationPolicy(ctx context.Context, in *SetReplicationPolicyRequest, opts ...grpc.CallOption) (*SetReplicationPolicyResponse, error)
	AnnounceRepoContent(ctx context.Context, in *AnnounceRepoContentRequest, opts ...grpc.CallOption) (*AnnounceRepoContentResponse, error)
	GetRefs(ctx context.Context, in *GetRefsRequest, opts ...grpc.CallOption) (*GetRefsResponse, error)
	GetRepoUsers(ctx context.Context, in *GetRepoUsersRequest, opts ...grpc.CallOption) (*GetRepoUsersResponse, error)
	UpdateRef(ctx context.Context, in *UpdateRefRequest, opts ...grpc.CallOption) (*UpdateRefResponse, error)
	RequestReplication(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*ReplicationResponse, error)
	GetRepoHistory(ctx context.Context, in *GetRepoHistoryRequest, opts ...grpc.CallOption) (*GetRepoHistoryResponse, error)
	GetRepoFiles(ctx context.Context, in *GetRepoFilesRequest, opts ...grpc.CallOption) (*GetRepoFilesResponse, error)
}

type nodeRPCClient struct {
	cc *grpc.ClientConn
}

func NewNodeRPCClient(cc *grpc.ClientConn) NodeRPCClient {
	return &nodeRPCClient{cc}
}

func (c *nodeRPCClient) SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...grpc.CallOption) (*SetUsernameResponse, error) {
	out := new(SetUsernameResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/SetUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) InitRepo(ctx context.Context, in *InitRepoRequest, opts ...grpc.CallOption) (*InitRepoResponse, error) {
	out := new(InitRepoResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/InitRepo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (NodeRPC_GetObjectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeRPC_serviceDesc.Streams[0], "/noderpc.NodeRPC/GetObject", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeRPCGetObjectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeRPC_GetObjectClient interface {
	Recv() (*GetObjectResponsePacket, error)
	grpc.ClientStream
}

type nodeRPCGetObjectClient struct {
	grpc.ClientStream
}

func (x *nodeRPCGetObjectClient) Recv() (*GetObjectResponsePacket, error) {
	m := new(GetObjectResponsePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeRPCClient) RegisterRepoID(ctx context.Context, in *RegisterRepoIDRequest, opts ...grpc.CallOption) (*RegisterRepoIDResponse, error) {
	out := new(RegisterRepoIDResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/RegisterRepoID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) TrackLocalRepo(ctx context.Context, in *TrackLocalRepoRequest, opts ...grpc.CallOption) (*TrackLocalRepoResponse, error) {
	out := new(TrackLocalRepoResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/TrackLocalRepo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetLocalRepos(ctx context.Context, in *GetLocalReposRequest, opts ...grpc.CallOption) (NodeRPC_GetLocalReposClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeRPC_serviceDesc.Streams[1], "/noderpc.NodeRPC/GetLocalRepos", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeRPCGetLocalReposClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeRPC_GetLocalReposClient interface {
	Recv() (*GetLocalReposResponsePacket, error)
	grpc.ClientStream
}

type nodeRPCGetLocalReposClient struct {
	grpc.ClientStream
}

func (x *nodeRPCGetLocalReposClient) Recv() (*GetLocalReposResponsePacket, error) {
	m := new(GetLocalReposResponsePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeRPCClient) SetReplicationPolicy(ctx context.Context, in *SetReplicationPolicyRequest, opts ...grpc.CallOption) (*SetReplicationPolicyResponse, error) {
	out := new(SetReplicationPolicyResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/SetReplicationPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) AnnounceRepoContent(ctx context.Context, in *AnnounceRepoContentRequest, opts ...grpc.CallOption) (*AnnounceRepoContentResponse, error) {
	out := new(AnnounceRepoContentResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/AnnounceRepoContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetRefs(ctx context.Context, in *GetRefsRequest, opts ...grpc.CallOption) (*GetRefsResponse, error) {
	out := new(GetRefsResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/GetRefs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetRepoUsers(ctx context.Context, in *GetRepoUsersRequest, opts ...grpc.CallOption) (*GetRepoUsersResponse, error) {
	out := new(GetRepoUsersResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/GetRepoUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) UpdateRef(ctx context.Context, in *UpdateRefRequest, opts ...grpc.CallOption) (*UpdateRefResponse, error) {
	out := new(UpdateRefResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/UpdateRef", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) RequestReplication(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*ReplicationResponse, error) {
	out := new(ReplicationResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/RequestReplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetRepoHistory(ctx context.Context, in *GetRepoHistoryRequest, opts ...grpc.CallOption) (*GetRepoHistoryResponse, error) {
	out := new(GetRepoHistoryResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/GetRepoHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetRepoFiles(ctx context.Context, in *GetRepoFilesRequest, opts ...grpc.CallOption) (*GetRepoFilesResponse, error) {
	out := new(GetRepoFilesResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/GetRepoFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeRPCServer is the server API for NodeRPC service.
type NodeRPCServer interface {
	SetUsername(context.Context, *SetUsernameRequest) (*SetUsernameResponse, error)
	InitRepo(context.Context, *InitRepoRequest) (*InitRepoResponse, error)
	GetObject(*GetObjectRequest, NodeRPC_GetObjectServer) error
	RegisterRepoID(context.Context, *RegisterRepoIDRequest) (*RegisterRepoIDResponse, error)
	TrackLocalRepo(context.Context, *TrackLocalRepoRequest) (*TrackLocalRepoResponse, error)
	GetLocalRepos(*GetLocalReposRequest, NodeRPC_GetLocalReposServer) error
	SetReplicationPolicy(context.Context, *SetReplicationPolicyRequest) (*SetReplicationPolicyResponse, error)
	AnnounceRepoContent(context.Context, *AnnounceRepoContentRequest) (*AnnounceRepoContentResponse, error)
	GetRefs(context.Context, *GetRefsRequest) (*GetRefsResponse, error)
	GetRepoUsers(context.Context, *GetRepoUsersRequest) (*GetRepoUsersResponse, error)
	UpdateRef(context.Context, *UpdateRefRequest) (*UpdateRefResponse, error)
	RequestReplication(context.Context, *ReplicationRequest) (*ReplicationResponse, error)
	GetRepoHistory(context.Context, *GetRepoHistoryRequest) (*GetRepoHistoryResponse, error)
	GetRepoFiles(context.Context, *GetRepoFilesRequest) (*GetRepoFilesResponse, error)
}

func RegisterNodeRPCServer(s *grpc.Server, srv NodeRPCServer) {
	s.RegisterService(&_NodeRPC_serviceDesc, srv)
}

func _NodeRPC_SetUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).SetUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/SetUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).SetUsername(ctx, req.(*SetUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_InitRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).InitRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/InitRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).InitRepo(ctx, req.(*InitRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeRPCServer).GetObject(m, &nodeRPCGetObjectServer{stream})
}

type NodeRPC_GetObjectServer interface {
	Send(*GetObjectResponsePacket) error
	grpc.ServerStream
}

type nodeRPCGetObjectServer struct {
	grpc.ServerStream
}

func (x *nodeRPCGetObjectServer) Send(m *GetObjectResponsePacket) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeRPC_RegisterRepoID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRepoIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).RegisterRepoID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/RegisterRepoID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).RegisterRepoID(ctx, req.(*RegisterRepoIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_TrackLocalRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackLocalRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).TrackLocalRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/TrackLocalRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).TrackLocalRepo(ctx, req.(*TrackLocalRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetLocalRepos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLocalReposRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeRPCServer).GetLocalRepos(m, &nodeRPCGetLocalReposServer{stream})
}

type NodeRPC_GetLocalReposServer interface {
	Send(*GetLocalReposResponsePacket) error
	grpc.ServerStream
}

type nodeRPCGetLocalReposServer struct {
	grpc.ServerStream
}

func (x *nodeRPCGetLocalReposServer) Send(m *GetLocalReposResponsePacket) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeRPC_SetReplicationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReplicationPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).SetReplicationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/SetReplicationPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).SetReplicationPolicy(ctx, req.(*SetReplicationPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_AnnounceRepoContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRepoContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).AnnounceRepoContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/AnnounceRepoContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).AnnounceRepoContent(ctx, req.(*AnnounceRepoContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetRefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).GetRefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/GetRefs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).GetRefs(ctx, req.(*GetRefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetRepoUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).GetRepoUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/GetRepoUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).GetRepoUsers(ctx, req.(*GetRepoUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_UpdateRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).UpdateRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/UpdateRef",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).UpdateRef(ctx, req.(*UpdateRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_RequestReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).RequestReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/RequestReplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).RequestReplication(ctx, req.(*ReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetRepoHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).GetRepoHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/GetRepoHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).GetRepoHistory(ctx, req.(*GetRepoHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetRepoFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).GetRepoFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/GetRepoFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).GetRepoFiles(ctx, req.(*GetRepoFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noderpc.NodeRPC",
	HandlerType: (*NodeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUsername",
			Handler:    _NodeRPC_SetUsername_Handler,
		},
		{
			MethodName: "InitRepo",
			Handler:    _NodeRPC_InitRepo_Handler,
		},
		{
			MethodName: "RegisterRepoID",
			Handler:    _NodeRPC_RegisterRepoID_Handler,
		},
		{
			MethodName: "TrackLocalRepo",
			Handler:    _NodeRPC_TrackLocalRepo_Handler,
		},
		{
			MethodName: "SetReplicationPolicy",
			Handler:    _NodeRPC_SetReplicationPolicy_Handler,
		},
		{
			MethodName: "AnnounceRepoContent",
			Handler:    _NodeRPC_AnnounceRepoContent_Handler,
		},
		{
			MethodName: "GetRefs",
			Handler:    _NodeRPC_GetRefs_Handler,
		},
		{
			MethodName: "GetRepoUsers",
			Handler:    _NodeRPC_GetRepoUsers_Handler,
		},
		{
			MethodName: "UpdateRef",
			Handler:    _NodeRPC_UpdateRef_Handler,
		},
		{
			MethodName: "RequestReplication",
			Handler:    _NodeRPC_RequestReplication_Handler,
		},
		{
			MethodName: "GetRepoHistory",
			Handler:    _NodeRPC_GetRepoHistory_Handler,
		},
		{
			MethodName: "GetRepoFiles",
			Handler:    _NodeRPC_GetRepoFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetObject",
			Handler:       _NodeRPC_GetObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLocalRepos",
			Handler:       _NodeRPC_GetLocalRepos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "noderpc.proto",
}

func init() { proto.RegisterFile("noderpc.proto", fileDescriptor_noderpc_8199278bb2b521db) }

var fileDescriptor_noderpc_8199278bb2b521db = []byte{
	// 976 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x6d, 0x6f, 0xdb, 0x36,
	0x10, 0xb6, 0x63, 0x27, 0xb6, 0xaf, 0xce, 0xcb, 0xe8, 0x38, 0xd5, 0x94, 0x97, 0x05, 0x6c, 0x37,
	0x64, 0xc0, 0xd6, 0x15, 0xed, 0xbe, 0x0d, 0xdb, 0x90, 0x3a, 0x68, 0xea, 0xa1, 0xeb, 0x32, 0x7a,
	0x05, 0x8a, 0x7d, 0x19, 0x18, 0x99, 0x76, 0xb4, 0xda, 0xa2, 0x2a, 0xd2, 0xc0, 0xb2, 0x6f, 0xfb,
	0x2b, 0xfb, 0xa5, 0x03, 0x29, 0x8a, 0xa6, 0x5e, 0x1c, 0x67, 0xfd, 0xc6, 0xbb, 0xe3, 0x3d, 0xe2,
	0x3d, 0x3c, 0xde, 0x03, 0xc1, 0x76, 0xc4, 0xc7, 0x2c, 0x89, 0x83, 0x27, 0x71, 0xc2, 0x25, 0x47,
	0x2d, 0x63, 0xe2, 0xa7, 0x80, 0x46, 0x4c, 0xbe, 0x15, 0x2c, 0x89, 0xe8, 0x9c, 0x11, 0xf6, 0x61,
	0xc1, 0x84, 0x44, 0x3e, 0xb4, 0x17, 0xc6, 0xe5, 0xd5, 0x4f, 0xeb, 0x67, 0x1d, 0x62, 0x6d, 0xdc,
	0x87, 0x5e, 0x2e, 0x43, 0xc4, 0x3c, 0x12, 0x0c, 0x7f, 0x0f, 0xbb, 0xc3, 0x28, 0x94, 0x84, 0xc5,
	0x3c, 0x43, 0x39, 0x80, 0xad, 0x84, 0xc5, 0x7c, 0x78, 0x61, 0x30, 0x8c, 0x85, 0x10, 0x34, 0x63,
	0x2a, 0x6f, 0xbc, 0x0d, 0xed, 0xd5, 0x6b, 0x8c, 0x60, 0x6f, 0x99, 0x6e, 0x20, 0x5f, 0xc2, 0xde,
	0x25, 0x93, 0xbf, 0x5c, 0xff, 0xc9, 0x02, 0xb9, 0x0e, 0xd3, 0x87, 0x36, 0xd7, 0x1b, 0x87, 0x17,
	0x1a, 0xb7, 0x4b, 0xac, 0x8d, 0xbf, 0x86, 0x87, 0x0e, 0x4e, 0x0a, 0x7e, 0x45, 0x83, 0xf7, 0x4c,
	0xaa, 0xa3, 0x8c, 0xa9, 0xa4, 0x1a, 0xac, 0x4b, 0xf4, 0x1a, 0x7f, 0x03, 0x7d, 0xc2, 0xa6, 0xa1,
	0x90, 0x2c, 0x21, 0x1a, 0x7c, 0xcd, 0xb7, 0xb1, 0x07, 0x07, 0xc5, 0x04, 0x53, 0xc1, 0x73, 0xe8,
	0xff, 0x96, 0xd0, 0xe0, 0xfd, 0x6b, 0x1e, 0xd0, 0x99, 0x4b, 0x8d, 0x0f, 0x6d, 0x95, 0x7c, 0xa5,
	0x68, 0x30, 0x04, 0x67, 0xb6, 0x82, 0x2b, 0x26, 0x19, 0xb8, 0x03, 0xd8, 0xbf, 0x64, 0xd2, 0xfa,
	0x85, 0x41, 0xc3, 0x43, 0x38, 0x2c, 0xf8, 0x73, 0x45, 0xfe, 0x9f, 0x7b, 0xf8, 0x03, 0x0e, 0x47,
	0x4c, 0x5d, 0xc3, 0x2c, 0x0c, 0xa8, 0x0c, 0x79, 0x74, 0xc5, 0x67, 0x61, 0x70, 0xbb, 0x8e, 0xfe,
	0x33, 0xd8, 0x15, 0x37, 0x7c, 0x31, 0x1b, 0x67, 0x99, 0x4c, 0xa3, 0xb6, 0x49, 0xd1, 0x8d, 0x4f,
	0xe0, 0xa8, 0xfa, 0x03, 0xa6, 0xc6, 0x6f, 0xc1, 0x3f, 0x8f, 0x22, 0xbe, 0x88, 0x02, 0xa6, 0x6a,
	0x19, 0xf0, 0x48, 0xb2, 0x68, 0xdd, 0xf5, 0xe3, 0x63, 0x38, 0xac, 0xcc, 0x32, 0xa0, 0x3f, 0x42,
	0x83, 0xb0, 0x09, 0xf2, 0xa0, 0x95, 0xb0, 0xc9, 0x9b, 0x65, 0x57, 0x67, 0x26, 0x3a, 0x01, 0x08,
	0xf8, 0x7c, 0x1e, 0xca, 0x57, 0x54, 0x64, 0x84, 0x38, 0x1e, 0xfc, 0x0e, 0x76, 0x2e, 0xd5, 0xa9,
	0x27, 0xe2, 0x1e, 0x8d, 0x18, 0xd3, 0x29, 0x1b, 0x85, 0x7f, 0xa7, 0x14, 0x34, 0x89, 0xb5, 0x53,
	0xc2, 0xa7, 0xcc, 0x6b, 0x68, 0xbf, 0x5e, 0xe3, 0x21, 0xec, 0x5a, 0xe4, 0xf4, 0xb4, 0x68, 0x1f,
	0x36, 0x25, 0x97, 0x74, 0xa6, 0x91, 0x9b, 0x24, 0x35, 0xd0, 0x29, 0x34, 0x13, 0x36, 0x11, 0xde,
	0xc6, 0x69, 0xe3, 0xec, 0xc1, 0xb3, 0xee, 0x93, 0xec, 0x41, 0x13, 0x36, 0x21, 0x3a, 0x82, 0xc7,
	0xb0, 0xf7, 0x36, 0x1e, 0x53, 0xc9, 0x94, 0x6b, 0xcd, 0x31, 0x1d, 0x2a, 0x36, 0xee, 0xa2, 0xa2,
	0x51, 0xa2, 0xa2, 0x07, 0x9f, 0x38, 0x5f, 0x31, 0x04, 0x7f, 0x80, 0x9e, 0xae, 0x22, 0xe6, 0x6a,
	0x30, 0x88, 0x7b, 0x4c, 0x00, 0x79, 0x1b, 0x67, 0x04, 0xe9, 0x75, 0x8e, 0xb8, 0xc6, 0x0a, 0xe2,
	0x9a, 0x0e, 0x71, 0x2f, 0xf4, 0x63, 0x70, 0x3e, 0x79, 0x27, 0x7b, 0xfb, 0xb0, 0xa9, 0x26, 0x58,
	0x4a, 0x5f, 0x87, 0xa4, 0x06, 0xfe, 0x0a, 0x90, 0xd3, 0x89, 0xeb, 0x9a, 0xac, 0x0f, 0xbd, 0xdc,
	0x6e, 0x53, 0xfb, 0x00, 0xfa, 0xe6, 0x20, 0xaf, 0x42, 0x21, 0x79, 0x72, 0x7b, 0xaf, 0xf9, 0x37,
	0xb5, 0xd5, 0xeb, 0x6a, 0xfe, 0x82, 0xad, 0x81, 0xe6, 0xb8, 0xc0, 0x7f, 0xbd, 0xc8, 0xbf, 0x42,
	0xa5, 0x0b, 0x79, 0xc3, 0x13, 0x73, 0x71, 0xc6, 0x52, 0x37, 0x3a, 0x67, 0x42, 0x64, 0xfd, 0xd5,
	0x21, 0x99, 0x89, 0x8e, 0xa0, 0x23, 0xc3, 0x39, 0x13, 0x92, 0xce, 0x63, 0x43, 0xe1, 0xd2, 0x81,
	0x07, 0x70, 0x50, 0x3c, 0xbe, 0x61, 0xf2, 0x4b, 0x68, 0xa5, 0xdf, 0x15, 0x5e, 0x5d, 0x37, 0xdd,
	0xae, 0x6d, 0xba, 0xf4, 0xac, 0x24, 0x8b, 0xe3, 0x73, 0x7b, 0xff, 0x2f, 0xc3, 0x19, 0x13, 0x1f,
	0xa3, 0x00, 0xff, 0xd6, 0xa1, 0xa9, 0x92, 0x55, 0xd0, 0x11, 0x1e, 0xbd, 0x56, 0xbe, 0x9b, 0xec,
	0x65, 0x76, 0x89, 0x5e, 0x2b, 0xdf, 0x9c, 0x8f, 0xd3, 0x6a, 0xb7, 0x89, 0x5e, 0x2b, 0x9f, 0x50,
	0x0d, 0x64, 0x1a, 0x45, 0xad, 0xd1, 0x17, 0xb0, 0xb3, 0x88, 0x84, 0xa4, 0x53, 0x36, 0x1e, 0x49,
	0x2a, 0x17, 0xc2, 0xdb, 0xd4, 0xc8, 0x05, 0x2f, 0xc2, 0xd0, 0xcd, 0xed, 0xda, 0xd2, 0xbb, 0x72,
	0x3e, 0xfc, 0x9d, 0x6d, 0x3a, 0x53, 0xa7, 0xa1, 0xea, 0x11, 0x6c, 0x4e, 0x94, 0xc3, 0x10, 0xb5,
	0x6d, 0x89, 0x52, 0xdb, 0x48, 0x1a, 0x7b, 0xf6, 0x4f, 0x07, 0x5a, 0x6f, 0xf8, 0x98, 0x91, 0xab,
	0x01, 0xfa, 0x09, 0x1e, 0x38, 0x2a, 0x8a, 0x0e, 0x6d, 0x42, 0x59, 0x8d, 0xfd, 0xa3, 0xea, 0xa0,
	0x69, 0xbf, 0x1a, 0x3a, 0x87, 0x76, 0xa6, 0x9d, 0xc8, 0xb3, 0x7b, 0x0b, 0x6a, 0xec, 0x7f, 0x5a,
	0x11, 0xb1, 0x10, 0xaf, 0xa1, 0x63, 0x25, 0x12, 0x2d, 0x77, 0x16, 0xe5, 0xd7, 0x3f, 0xad, 0x0a,
	0xb9, 0x62, 0x83, 0x6b, 0x4f, 0xeb, 0x68, 0x04, 0x3b, 0x79, 0x41, 0x44, 0x27, 0xce, 0xb8, 0xaa,
	0x90, 0x56, 0xff, 0xb3, 0x95, 0x71, 0x7b, 0xc4, 0x11, 0xec, 0xe4, 0x65, 0xd1, 0x01, 0xad, 0x14,
	0x59, 0x07, 0x74, 0x85, 0x9e, 0xd6, 0xd0, 0x3b, 0xd8, 0xce, 0x29, 0x27, 0x3a, 0x76, 0x0b, 0x2c,
	0x29, 0xad, 0xff, 0x78, 0x55, 0xb8, 0xc4, 0x01, 0x83, 0xfd, 0x2a, 0x9d, 0x43, 0x8f, 0xdd, 0xcb,
	0x5c, 0xa5, 0xb3, 0xfe, 0xe7, 0x6b, 0x76, 0xd9, 0x02, 0xae, 0xa1, 0x57, 0x21, 0x7c, 0xe8, 0x91,
	0xcd, 0x5f, 0x2d, 0xa6, 0x4e, 0x31, 0x77, 0x69, 0x67, 0x0d, 0xfd, 0x00, 0x2d, 0x23, 0x51, 0xe8,
	0xa1, 0x5b, 0xbf, 0x23, 0x87, 0xbe, 0x57, 0x0e, 0xd8, 0xfc, 0x9f, 0xa1, 0xeb, 0x4e, 0x6a, 0x74,
	0x94, 0xdf, 0x9b, 0xd7, 0x0c, 0xff, 0x78, 0x45, 0xd4, 0xc2, 0x5d, 0x40, 0xc7, 0x0a, 0x90, 0xd3,
	0xab, 0x45, 0xe9, 0xf3, 0xfd, 0xaa, 0x90, 0x45, 0xf9, 0x55, 0x8d, 0x7e, 0xbd, 0xd1, 0xa1, 0xd7,
	0x79, 0x87, 0x65, 0x5d, 0x70, 0xde, 0x61, 0x95, 0x0c, 0xe8, 0x0e, 0xcd, 0x4f, 0x52, 0xa7, 0x43,
	0x2b, 0x15, 0xc2, 0xe9, 0xd0, 0xea, 0x11, 0x9c, 0x23, 0x4f, 0x4f, 0x9c, 0x32, 0x79, 0xee, 0xc0,
	0x2d, 0x93, 0x97, 0x1b, 0x53, 0xb8, 0xf6, 0xa2, 0xf9, 0xfb, 0x46, 0x7c, 0x7d, 0xbd, 0xa5, 0xff,
	0x02, 0x9e, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x22, 0x7d, 0xb4, 0x16, 0x0c, 0x00, 0x00,
}
