// Code generated by protoc-gen-go. DO NOT EDIT.
// source: noderpc.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUsernameRequest) Reset()         { *m = SetUsernameRequest{} }
func (m *SetUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*SetUsernameRequest) ProtoMessage()    {}
func (*SetUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{0}
}
func (m *SetUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUsernameRequest.Unmarshal(m, b)
}
func (m *SetUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUsernameRequest.Marshal(b, m, deterministic)
}
func (dst *SetUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUsernameRequest.Merge(dst, src)
}
func (m *SetUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_SetUsernameRequest.Size(m)
}
func (m *SetUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUsernameRequest proto.InternalMessageInfo

func (m *SetUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type SetUsernameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUsernameResponse) Reset()         { *m = SetUsernameResponse{} }
func (m *SetUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*SetUsernameResponse) ProtoMessage()    {}
func (*SetUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{1}
}
func (m *SetUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUsernameResponse.Unmarshal(m, b)
}
func (m *SetUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUsernameResponse.Marshal(b, m, deterministic)
}
func (dst *SetUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUsernameResponse.Merge(dst, src)
}
func (m *SetUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_SetUsernameResponse.Size(m)
}
func (m *SetUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUsernameResponse proto.InternalMessageInfo

type GetObjectRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	ObjectID             []byte   `protobuf:"bytes,2,opt,name=objectID,proto3" json:"objectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectRequest) Reset()         { *m = GetObjectRequest{} }
func (m *GetObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjectRequest) ProtoMessage()    {}
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{2}
}
func (m *GetObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectRequest.Unmarshal(m, b)
}
func (m *GetObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectRequest.Marshal(b, m, deterministic)
}
func (dst *GetObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectRequest.Merge(dst, src)
}
func (m *GetObjectRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjectRequest.Size(m)
}
func (m *GetObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectRequest proto.InternalMessageInfo

func (m *GetObjectRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetObjectRequest) GetObjectID() []byte {
	if m != nil {
		return m.ObjectID
	}
	return nil
}

type GetObjectResponsePacket struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectResponsePacket) Reset()         { *m = GetObjectResponsePacket{} }
func (m *GetObjectResponsePacket) String() string { return proto.CompactTextString(m) }
func (*GetObjectResponsePacket) ProtoMessage()    {}
func (*GetObjectResponsePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{3}
}
func (m *GetObjectResponsePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectResponsePacket.Unmarshal(m, b)
}
func (m *GetObjectResponsePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectResponsePacket.Marshal(b, m, deterministic)
}
func (dst *GetObjectResponsePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectResponsePacket.Merge(dst, src)
}
func (m *GetObjectResponsePacket) XXX_Size() int {
	return xxx_messageInfo_GetObjectResponsePacket.Size(m)
}
func (m *GetObjectResponsePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectResponsePacket.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectResponsePacket proto.InternalMessageInfo

func (m *GetObjectResponsePacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RegisterRepoIDRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRepoIDRequest) Reset()         { *m = RegisterRepoIDRequest{} }
func (m *RegisterRepoIDRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRepoIDRequest) ProtoMessage()    {}
func (*RegisterRepoIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{4}
}
func (m *RegisterRepoIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRepoIDRequest.Unmarshal(m, b)
}
func (m *RegisterRepoIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRepoIDRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRepoIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRepoIDRequest.Merge(dst, src)
}
func (m *RegisterRepoIDRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRepoIDRequest.Size(m)
}
func (m *RegisterRepoIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRepoIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRepoIDRequest proto.InternalMessageInfo

func (m *RegisterRepoIDRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

type RegisterRepoIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRepoIDResponse) Reset()         { *m = RegisterRepoIDResponse{} }
func (m *RegisterRepoIDResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterRepoIDResponse) ProtoMessage()    {}
func (*RegisterRepoIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{5}
}
func (m *RegisterRepoIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRepoIDResponse.Unmarshal(m, b)
}
func (m *RegisterRepoIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRepoIDResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterRepoIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRepoIDResponse.Merge(dst, src)
}
func (m *RegisterRepoIDResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterRepoIDResponse.Size(m)
}
func (m *RegisterRepoIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRepoIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRepoIDResponse proto.InternalMessageInfo

type TrackLocalRepoRequest struct {
	RepoPath             string   `protobuf:"bytes,1,opt,name=repoPath,proto3" json:"repoPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackLocalRepoRequest) Reset()         { *m = TrackLocalRepoRequest{} }
func (m *TrackLocalRepoRequest) String() string { return proto.CompactTextString(m) }
func (*TrackLocalRepoRequest) ProtoMessage()    {}
func (*TrackLocalRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{6}
}
func (m *TrackLocalRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackLocalRepoRequest.Unmarshal(m, b)
}
func (m *TrackLocalRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackLocalRepoRequest.Marshal(b, m, deterministic)
}
func (dst *TrackLocalRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackLocalRepoRequest.Merge(dst, src)
}
func (m *TrackLocalRepoRequest) XXX_Size() int {
	return xxx_messageInfo_TrackLocalRepoRequest.Size(m)
}
func (m *TrackLocalRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackLocalRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrackLocalRepoRequest proto.InternalMessageInfo

func (m *TrackLocalRepoRequest) GetRepoPath() string {
	if m != nil {
		return m.RepoPath
	}
	return ""
}

type TrackLocalRepoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackLocalRepoResponse) Reset()         { *m = TrackLocalRepoResponse{} }
func (m *TrackLocalRepoResponse) String() string { return proto.CompactTextString(m) }
func (*TrackLocalRepoResponse) ProtoMessage()    {}
func (*TrackLocalRepoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{7}
}
func (m *TrackLocalRepoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackLocalRepoResponse.Unmarshal(m, b)
}
func (m *TrackLocalRepoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackLocalRepoResponse.Marshal(b, m, deterministic)
}
func (dst *TrackLocalRepoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackLocalRepoResponse.Merge(dst, src)
}
func (m *TrackLocalRepoResponse) XXX_Size() int {
	return xxx_messageInfo_TrackLocalRepoResponse.Size(m)
}
func (m *TrackLocalRepoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackLocalRepoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrackLocalRepoResponse proto.InternalMessageInfo

type GetLocalReposRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLocalReposRequest) Reset()         { *m = GetLocalReposRequest{} }
func (m *GetLocalReposRequest) String() string { return proto.CompactTextString(m) }
func (*GetLocalReposRequest) ProtoMessage()    {}
func (*GetLocalReposRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{8}
}
func (m *GetLocalReposRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocalReposRequest.Unmarshal(m, b)
}
func (m *GetLocalReposRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocalReposRequest.Marshal(b, m, deterministic)
}
func (dst *GetLocalReposRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocalReposRequest.Merge(dst, src)
}
func (m *GetLocalReposRequest) XXX_Size() int {
	return xxx_messageInfo_GetLocalReposRequest.Size(m)
}
func (m *GetLocalReposRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocalReposRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocalReposRequest proto.InternalMessageInfo

type GetLocalReposResponsePacket struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLocalReposResponsePacket) Reset()         { *m = GetLocalReposResponsePacket{} }
func (m *GetLocalReposResponsePacket) String() string { return proto.CompactTextString(m) }
func (*GetLocalReposResponsePacket) ProtoMessage()    {}
func (*GetLocalReposResponsePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{9}
}
func (m *GetLocalReposResponsePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocalReposResponsePacket.Unmarshal(m, b)
}
func (m *GetLocalReposResponsePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocalReposResponsePacket.Marshal(b, m, deterministic)
}
func (dst *GetLocalReposResponsePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocalReposResponsePacket.Merge(dst, src)
}
func (m *GetLocalReposResponsePacket) XXX_Size() int {
	return xxx_messageInfo_GetLocalReposResponsePacket.Size(m)
}
func (m *GetLocalReposResponsePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocalReposResponsePacket.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocalReposResponsePacket proto.InternalMessageInfo

func (m *GetLocalReposResponsePacket) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetLocalReposResponsePacket) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SetReplicationPolicyRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	ShouldReplicate      bool     `protobuf:"varint,2,opt,name=shouldReplicate,proto3" json:"shouldReplicate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReplicationPolicyRequest) Reset()         { *m = SetReplicationPolicyRequest{} }
func (m *SetReplicationPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*SetReplicationPolicyRequest) ProtoMessage()    {}
func (*SetReplicationPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{10}
}
func (m *SetReplicationPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReplicationPolicyRequest.Unmarshal(m, b)
}
func (m *SetReplicationPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReplicationPolicyRequest.Marshal(b, m, deterministic)
}
func (dst *SetReplicationPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReplicationPolicyRequest.Merge(dst, src)
}
func (m *SetReplicationPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_SetReplicationPolicyRequest.Size(m)
}
func (m *SetReplicationPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReplicationPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetReplicationPolicyRequest proto.InternalMessageInfo

func (m *SetReplicationPolicyRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *SetReplicationPolicyRequest) GetShouldReplicate() bool {
	if m != nil {
		return m.ShouldReplicate
	}
	return false
}

type SetReplicationPolicyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReplicationPolicyResponse) Reset()         { *m = SetReplicationPolicyResponse{} }
func (m *SetReplicationPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*SetReplicationPolicyResponse) ProtoMessage()    {}
func (*SetReplicationPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{11}
}
func (m *SetReplicationPolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReplicationPolicyResponse.Unmarshal(m, b)
}
func (m *SetReplicationPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReplicationPolicyResponse.Marshal(b, m, deterministic)
}
func (dst *SetReplicationPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReplicationPolicyResponse.Merge(dst, src)
}
func (m *SetReplicationPolicyResponse) XXX_Size() int {
	return xxx_messageInfo_SetReplicationPolicyResponse.Size(m)
}
func (m *SetReplicationPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReplicationPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetReplicationPolicyResponse proto.InternalMessageInfo

type AnnounceRepoContentRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceRepoContentRequest) Reset()         { *m = AnnounceRepoContentRequest{} }
func (m *AnnounceRepoContentRequest) String() string { return proto.CompactTextString(m) }
func (*AnnounceRepoContentRequest) ProtoMessage()    {}
func (*AnnounceRepoContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{12}
}
func (m *AnnounceRepoContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceRepoContentRequest.Unmarshal(m, b)
}
func (m *AnnounceRepoContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceRepoContentRequest.Marshal(b, m, deterministic)
}
func (dst *AnnounceRepoContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceRepoContentRequest.Merge(dst, src)
}
func (m *AnnounceRepoContentRequest) XXX_Size() int {
	return xxx_messageInfo_AnnounceRepoContentRequest.Size(m)
}
func (m *AnnounceRepoContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceRepoContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceRepoContentRequest proto.InternalMessageInfo

func (m *AnnounceRepoContentRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

type AnnounceRepoContentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceRepoContentResponse) Reset()         { *m = AnnounceRepoContentResponse{} }
func (m *AnnounceRepoContentResponse) String() string { return proto.CompactTextString(m) }
func (*AnnounceRepoContentResponse) ProtoMessage()    {}
func (*AnnounceRepoContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{13}
}
func (m *AnnounceRepoContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceRepoContentResponse.Unmarshal(m, b)
}
func (m *AnnounceRepoContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceRepoContentResponse.Marshal(b, m, deterministic)
}
func (dst *AnnounceRepoContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceRepoContentResponse.Merge(dst, src)
}
func (m *AnnounceRepoContentResponse) XXX_Size() int {
	return xxx_messageInfo_AnnounceRepoContentResponse.Size(m)
}
func (m *AnnounceRepoContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceRepoContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceRepoContentResponse proto.InternalMessageInfo

type Ref struct {
	RefName              string   `protobuf:"bytes,1,opt,name=refName,proto3" json:"refName,omitempty"`
	CommitHash           string   `protobuf:"bytes,2,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ref) Reset()         { *m = Ref{} }
func (m *Ref) String() string { return proto.CompactTextString(m) }
func (*Ref) ProtoMessage()    {}
func (*Ref) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{14}
}
func (m *Ref) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ref.Unmarshal(m, b)
}
func (m *Ref) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ref.Marshal(b, m, deterministic)
}
func (dst *Ref) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ref.Merge(dst, src)
}
func (m *Ref) XXX_Size() int {
	return xxx_messageInfo_Ref.Size(m)
}
func (m *Ref) XXX_DiscardUnknown() {
	xxx_messageInfo_Ref.DiscardUnknown(m)
}

var xxx_messageInfo_Ref proto.InternalMessageInfo

func (m *Ref) GetRefName() string {
	if m != nil {
		return m.RefName
	}
	return ""
}

func (m *Ref) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

type GetRefsRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	Page                 uint64   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRefsRequest) Reset()         { *m = GetRefsRequest{} }
func (m *GetRefsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRefsRequest) ProtoMessage()    {}
func (*GetRefsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{15}
}
func (m *GetRefsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefsRequest.Unmarshal(m, b)
}
func (m *GetRefsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefsRequest.Marshal(b, m, deterministic)
}
func (dst *GetRefsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefsRequest.Merge(dst, src)
}
func (m *GetRefsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRefsRequest.Size(m)
}
func (m *GetRefsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefsRequest proto.InternalMessageInfo

func (m *GetRefsRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *GetRefsRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetRefsResponse struct {
	NumRefs              uint64   `protobuf:"varint,1,opt,name=numRefs,proto3" json:"numRefs,omitempty"`
	Ref                  []*Ref   `protobuf:"bytes,2,rep,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRefsResponse) Reset()         { *m = GetRefsResponse{} }
func (m *GetRefsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRefsResponse) ProtoMessage()    {}
func (*GetRefsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{16}
}
func (m *GetRefsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefsResponse.Unmarshal(m, b)
}
func (m *GetRefsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefsResponse.Marshal(b, m, deterministic)
}
func (dst *GetRefsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefsResponse.Merge(dst, src)
}
func (m *GetRefsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRefsResponse.Size(m)
}
func (m *GetRefsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefsResponse proto.InternalMessageInfo

func (m *GetRefsResponse) GetNumRefs() uint64 {
	if m != nil {
		return m.NumRefs
	}
	return 0
}

func (m *GetRefsResponse) GetRef() []*Ref {
	if m != nil {
		return m.Ref
	}
	return nil
}

type UpdateRefRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	RefName              string   `protobuf:"bytes,2,opt,name=refName,proto3" json:"refName,omitempty"`
	CommitHash           string   `protobuf:"bytes,3,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRefRequest) Reset()         { *m = UpdateRefRequest{} }
func (m *UpdateRefRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRefRequest) ProtoMessage()    {}
func (*UpdateRefRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{17}
}
func (m *UpdateRefRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRefRequest.Unmarshal(m, b)
}
func (m *UpdateRefRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRefRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRefRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRefRequest.Merge(dst, src)
}
func (m *UpdateRefRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRefRequest.Size(m)
}
func (m *UpdateRefRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRefRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRefRequest proto.InternalMessageInfo

func (m *UpdateRefRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

func (m *UpdateRefRequest) GetRefName() string {
	if m != nil {
		return m.RefName
	}
	return ""
}

func (m *UpdateRefRequest) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

type UpdateRefResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRefResponse) Reset()         { *m = UpdateRefResponse{} }
func (m *UpdateRefResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRefResponse) ProtoMessage()    {}
func (*UpdateRefResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{18}
}
func (m *UpdateRefResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRefResponse.Unmarshal(m, b)
}
func (m *UpdateRefResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRefResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateRefResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRefResponse.Merge(dst, src)
}
func (m *UpdateRefResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRefResponse.Size(m)
}
func (m *UpdateRefResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRefResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRefResponse proto.InternalMessageInfo

type ReplicationRequest struct {
	RepoID               string   `protobuf:"bytes,1,opt,name=repoID,proto3" json:"repoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationRequest) Reset()         { *m = ReplicationRequest{} }
func (m *ReplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicationRequest) ProtoMessage()    {}
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{19}
}
func (m *ReplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationRequest.Unmarshal(m, b)
}
func (m *ReplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationRequest.Marshal(b, m, deterministic)
}
func (dst *ReplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationRequest.Merge(dst, src)
}
func (m *ReplicationRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicationRequest.Size(m)
}
func (m *ReplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationRequest proto.InternalMessageInfo

func (m *ReplicationRequest) GetRepoID() string {
	if m != nil {
		return m.RepoID
	}
	return ""
}

type ReplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationResponse) Reset()         { *m = ReplicationResponse{} }
func (m *ReplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicationResponse) ProtoMessage()    {}
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_noderpc_a5c30537f037df7b, []int{20}
}
func (m *ReplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationResponse.Unmarshal(m, b)
}
func (m *ReplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationResponse.Marshal(b, m, deterministic)
}
func (dst *ReplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationResponse.Merge(dst, src)
}
func (m *ReplicationResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicationResponse.Size(m)
}
func (m *ReplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SetUsernameRequest)(nil), "noderpc.SetUsernameRequest")
	proto.RegisterType((*SetUsernameResponse)(nil), "noderpc.SetUsernameResponse")
	proto.RegisterType((*GetObjectRequest)(nil), "noderpc.GetObjectRequest")
	proto.RegisterType((*GetObjectResponsePacket)(nil), "noderpc.GetObjectResponsePacket")
	proto.RegisterType((*RegisterRepoIDRequest)(nil), "noderpc.RegisterRepoIDRequest")
	proto.RegisterType((*RegisterRepoIDResponse)(nil), "noderpc.RegisterRepoIDResponse")
	proto.RegisterType((*TrackLocalRepoRequest)(nil), "noderpc.TrackLocalRepoRequest")
	proto.RegisterType((*TrackLocalRepoResponse)(nil), "noderpc.TrackLocalRepoResponse")
	proto.RegisterType((*GetLocalReposRequest)(nil), "noderpc.GetLocalReposRequest")
	proto.RegisterType((*GetLocalReposResponsePacket)(nil), "noderpc.GetLocalReposResponsePacket")
	proto.RegisterType((*SetReplicationPolicyRequest)(nil), "noderpc.SetReplicationPolicyRequest")
	proto.RegisterType((*SetReplicationPolicyResponse)(nil), "noderpc.SetReplicationPolicyResponse")
	proto.RegisterType((*AnnounceRepoContentRequest)(nil), "noderpc.AnnounceRepoContentRequest")
	proto.RegisterType((*AnnounceRepoContentResponse)(nil), "noderpc.AnnounceRepoContentResponse")
	proto.RegisterType((*Ref)(nil), "noderpc.Ref")
	proto.RegisterType((*GetRefsRequest)(nil), "noderpc.GetRefsRequest")
	proto.RegisterType((*GetRefsResponse)(nil), "noderpc.GetRefsResponse")
	proto.RegisterType((*UpdateRefRequest)(nil), "noderpc.UpdateRefRequest")
	proto.RegisterType((*UpdateRefResponse)(nil), "noderpc.UpdateRefResponse")
	proto.RegisterType((*ReplicationRequest)(nil), "noderpc.ReplicationRequest")
	proto.RegisterType((*ReplicationResponse)(nil), "noderpc.ReplicationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeRPCClient is the client API for NodeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeRPCClient interface {
	SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...grpc.CallOption) (*SetUsernameResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (NodeRPC_GetObjectClient, error)
	RegisterRepoID(ctx context.Context, in *RegisterRepoIDRequest, opts ...grpc.CallOption) (*RegisterRepoIDResponse, error)
	TrackLocalRepo(ctx context.Context, in *TrackLocalRepoRequest, opts ...grpc.CallOption) (*TrackLocalRepoResponse, error)
	GetLocalRepos(ctx context.Context, in *GetLocalReposRequest, opts ...grpc.CallOption) (NodeRPC_GetLocalReposClient, error)
	SetReplicationPolicy(ctx context.Context, in *SetReplicationPolicyRequest, opts ...grpc.CallOption) (*SetReplicationPolicyResponse, error)
	AnnounceRepoContent(ctx context.Context, in *AnnounceRepoContentRequest, opts ...grpc.CallOption) (*AnnounceRepoContentResponse, error)
	GetRefs(ctx context.Context, in *GetRefsRequest, opts ...grpc.CallOption) (*GetRefsResponse, error)
	UpdateRef(ctx context.Context, in *UpdateRefRequest, opts ...grpc.CallOption) (*UpdateRefResponse, error)
	RequestReplication(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*ReplicationResponse, error)
}

type nodeRPCClient struct {
	cc *grpc.ClientConn
}

func NewNodeRPCClient(cc *grpc.ClientConn) NodeRPCClient {
	return &nodeRPCClient{cc}
}

func (c *nodeRPCClient) SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...grpc.CallOption) (*SetUsernameResponse, error) {
	out := new(SetUsernameResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/SetUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (NodeRPC_GetObjectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeRPC_serviceDesc.Streams[0], "/noderpc.NodeRPC/GetObject", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeRPCGetObjectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeRPC_GetObjectClient interface {
	Recv() (*GetObjectResponsePacket, error)
	grpc.ClientStream
}

type nodeRPCGetObjectClient struct {
	grpc.ClientStream
}

func (x *nodeRPCGetObjectClient) Recv() (*GetObjectResponsePacket, error) {
	m := new(GetObjectResponsePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeRPCClient) RegisterRepoID(ctx context.Context, in *RegisterRepoIDRequest, opts ...grpc.CallOption) (*RegisterRepoIDResponse, error) {
	out := new(RegisterRepoIDResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/RegisterRepoID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) TrackLocalRepo(ctx context.Context, in *TrackLocalRepoRequest, opts ...grpc.CallOption) (*TrackLocalRepoResponse, error) {
	out := new(TrackLocalRepoResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/TrackLocalRepo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetLocalRepos(ctx context.Context, in *GetLocalReposRequest, opts ...grpc.CallOption) (NodeRPC_GetLocalReposClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeRPC_serviceDesc.Streams[1], "/noderpc.NodeRPC/GetLocalRepos", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeRPCGetLocalReposClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeRPC_GetLocalReposClient interface {
	Recv() (*GetLocalReposResponsePacket, error)
	grpc.ClientStream
}

type nodeRPCGetLocalReposClient struct {
	grpc.ClientStream
}

func (x *nodeRPCGetLocalReposClient) Recv() (*GetLocalReposResponsePacket, error) {
	m := new(GetLocalReposResponsePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeRPCClient) SetReplicationPolicy(ctx context.Context, in *SetReplicationPolicyRequest, opts ...grpc.CallOption) (*SetReplicationPolicyResponse, error) {
	out := new(SetReplicationPolicyResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/SetReplicationPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) AnnounceRepoContent(ctx context.Context, in *AnnounceRepoContentRequest, opts ...grpc.CallOption) (*AnnounceRepoContentResponse, error) {
	out := new(AnnounceRepoContentResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/AnnounceRepoContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) GetRefs(ctx context.Context, in *GetRefsRequest, opts ...grpc.CallOption) (*GetRefsResponse, error) {
	out := new(GetRefsResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/GetRefs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) UpdateRef(ctx context.Context, in *UpdateRefRequest, opts ...grpc.CallOption) (*UpdateRefResponse, error) {
	out := new(UpdateRefResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/UpdateRef", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) RequestReplication(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*ReplicationResponse, error) {
	out := new(ReplicationResponse)
	err := c.cc.Invoke(ctx, "/noderpc.NodeRPC/RequestReplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeRPCServer is the server API for NodeRPC service.
type NodeRPCServer interface {
	SetUsername(context.Context, *SetUsernameRequest) (*SetUsernameResponse, error)
	GetObject(*GetObjectRequest, NodeRPC_GetObjectServer) error
	RegisterRepoID(context.Context, *RegisterRepoIDRequest) (*RegisterRepoIDResponse, error)
	TrackLocalRepo(context.Context, *TrackLocalRepoRequest) (*TrackLocalRepoResponse, error)
	GetLocalRepos(*GetLocalReposRequest, NodeRPC_GetLocalReposServer) error
	SetReplicationPolicy(context.Context, *SetReplicationPolicyRequest) (*SetReplicationPolicyResponse, error)
	AnnounceRepoContent(context.Context, *AnnounceRepoContentRequest) (*AnnounceRepoContentResponse, error)
	GetRefs(context.Context, *GetRefsRequest) (*GetRefsResponse, error)
	UpdateRef(context.Context, *UpdateRefRequest) (*UpdateRefResponse, error)
	RequestReplication(context.Context, *ReplicationRequest) (*ReplicationResponse, error)
}

func RegisterNodeRPCServer(s *grpc.Server, srv NodeRPCServer) {
	s.RegisterService(&_NodeRPC_serviceDesc, srv)
}

func _NodeRPC_SetUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).SetUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/SetUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).SetUsername(ctx, req.(*SetUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeRPCServer).GetObject(m, &nodeRPCGetObjectServer{stream})
}

type NodeRPC_GetObjectServer interface {
	Send(*GetObjectResponsePacket) error
	grpc.ServerStream
}

type nodeRPCGetObjectServer struct {
	grpc.ServerStream
}

func (x *nodeRPCGetObjectServer) Send(m *GetObjectResponsePacket) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeRPC_RegisterRepoID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRepoIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).RegisterRepoID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/RegisterRepoID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).RegisterRepoID(ctx, req.(*RegisterRepoIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_TrackLocalRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackLocalRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).TrackLocalRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/TrackLocalRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).TrackLocalRepo(ctx, req.(*TrackLocalRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetLocalRepos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLocalReposRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeRPCServer).GetLocalRepos(m, &nodeRPCGetLocalReposServer{stream})
}

type NodeRPC_GetLocalReposServer interface {
	Send(*GetLocalReposResponsePacket) error
	grpc.ServerStream
}

type nodeRPCGetLocalReposServer struct {
	grpc.ServerStream
}

func (x *nodeRPCGetLocalReposServer) Send(m *GetLocalReposResponsePacket) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeRPC_SetReplicationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReplicationPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).SetReplicationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/SetReplicationPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).SetReplicationPolicy(ctx, req.(*SetReplicationPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_AnnounceRepoContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRepoContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).AnnounceRepoContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/AnnounceRepoContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).AnnounceRepoContent(ctx, req.(*AnnounceRepoContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_GetRefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).GetRefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/GetRefs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).GetRefs(ctx, req.(*GetRefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_UpdateRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).UpdateRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/UpdateRef",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).UpdateRef(ctx, req.(*UpdateRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_RequestReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).RequestReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noderpc.NodeRPC/RequestReplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).RequestReplication(ctx, req.(*ReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noderpc.NodeRPC",
	HandlerType: (*NodeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUsername",
			Handler:    _NodeRPC_SetUsername_Handler,
		},
		{
			MethodName: "RegisterRepoID",
			Handler:    _NodeRPC_RegisterRepoID_Handler,
		},
		{
			MethodName: "TrackLocalRepo",
			Handler:    _NodeRPC_TrackLocalRepo_Handler,
		},
		{
			MethodName: "SetReplicationPolicy",
			Handler:    _NodeRPC_SetReplicationPolicy_Handler,
		},
		{
			MethodName: "AnnounceRepoContent",
			Handler:    _NodeRPC_AnnounceRepoContent_Handler,
		},
		{
			MethodName: "GetRefs",
			Handler:    _NodeRPC_GetRefs_Handler,
		},
		{
			MethodName: "UpdateRef",
			Handler:    _NodeRPC_UpdateRef_Handler,
		},
		{
			MethodName: "RequestReplication",
			Handler:    _NodeRPC_RequestReplication_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetObject",
			Handler:       _NodeRPC_GetObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLocalRepos",
			Handler:       _NodeRPC_GetLocalRepos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "noderpc.proto",
}

func init() { proto.RegisterFile("noderpc.proto", fileDescriptor_noderpc_a5c30537f037df7b) }

var fileDescriptor_noderpc_a5c30537f037df7b = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xee, 0x2f, 0xad, 0xdb, 0xed, 0x27, 0xee, 0xba, 0x95, 0x74, 0x2b, 0x95, 0x19, 0x52, 0x1f,
	0x60, 0x4c, 0x1b, 0x8f, 0x08, 0x04, 0x9b, 0x18, 0x85, 0x69, 0x14, 0x97, 0x49, 0x88, 0x17, 0x94,
	0xa6, 0xd7, 0xad, 0xac, 0x8d, 0x43, 0xe2, 0x3e, 0xf0, 0x37, 0xf2, 0x4f, 0x21, 0xbb, 0x8e, 0x71,
	0x9b, 0x64, 0x79, 0xcb, 0xdd, 0xf9, 0x3e, 0xdf, 0x77, 0xe7, 0xef, 0x02, 0x9b, 0x3e, 0x1f, 0x62,
	0x18, 0x78, 0xc7, 0x41, 0xc8, 0x05, 0x27, 0x55, 0x6d, 0xd2, 0x13, 0x20, 0x7d, 0x14, 0x37, 0x11,
	0x86, 0xbe, 0x3b, 0x45, 0x86, 0xbf, 0x67, 0x18, 0x09, 0xe2, 0xc0, 0xea, 0x4c, 0xbb, 0x1a, 0xc5,
	0x76, 0xb1, 0xb3, 0xc6, 0x8c, 0x4d, 0xeb, 0x50, 0x5b, 0xc8, 0x88, 0x02, 0xee, 0x47, 0x48, 0x3f,
	0xc0, 0xce, 0x25, 0x8a, 0x2f, 0x83, 0x5f, 0xe8, 0x89, 0x18, 0x66, 0x0f, 0x56, 0x42, 0x0c, 0x78,
	0xf7, 0x42, 0x83, 0x68, 0x4b, 0xc2, 0x73, 0x75, 0xb0, 0x7b, 0xd1, 0x28, 0xb5, 0x8b, 0x9d, 0x0d,
	0x66, 0x6c, 0xfa, 0x02, 0xf6, 0x2d, 0x9c, 0x39, 0x78, 0xcf, 0xf5, 0xee, 0x51, 0x10, 0x02, 0x95,
	0xa1, 0x2b, 0x5c, 0x05, 0xb6, 0xc1, 0xd4, 0x37, 0x7d, 0x09, 0x75, 0x86, 0xb7, 0xe3, 0x48, 0x60,
	0xc8, 0x14, 0x78, 0xce, 0xdd, 0xb4, 0x01, 0x7b, 0xcb, 0x09, 0x9a, 0xc1, 0x19, 0xd4, 0xbf, 0x85,
	0xae, 0x77, 0x7f, 0xc5, 0x3d, 0x77, 0x22, 0x63, 0x56, 0x37, 0x64, 0x72, 0xcf, 0x15, 0x77, 0x71,
	0x37, 0x62, 0x5b, 0xc2, 0x2d, 0x27, 0x69, 0xb8, 0x3d, 0xd8, 0xbd, 0x44, 0x61, 0xfc, 0x91, 0x46,
	0xa3, 0x5d, 0x68, 0x2e, 0xf9, 0x17, 0x48, 0x66, 0xf5, 0x8c, 0x40, 0x25, 0x90, 0x05, 0x94, 0x94,
	0x57, 0x7d, 0xd3, 0x9f, 0xd0, 0xec, 0xa3, 0x60, 0x18, 0x4c, 0xc6, 0x9e, 0x2b, 0xc6, 0xdc, 0xef,
	0xf1, 0xc9, 0xd8, 0xfb, 0x93, 0xd7, 0xfe, 0x0e, 0x6c, 0x47, 0x77, 0x7c, 0x36, 0x19, 0xc6, 0x99,
	0xa8, 0x50, 0x57, 0xd9, 0xb2, 0x9b, 0xb6, 0xe0, 0x20, 0xfd, 0x02, 0xcd, 0xf1, 0x15, 0x38, 0xef,
	0x7c, 0x9f, 0xcf, 0x7c, 0x0f, 0x25, 0x97, 0x73, 0xee, 0x0b, 0xf4, 0xf3, 0xc6, 0x4f, 0x0f, 0xa1,
	0x99, 0x9a, 0xa5, 0x41, 0xdf, 0x42, 0x99, 0xe1, 0x88, 0x34, 0xa0, 0x1a, 0xe2, 0xe8, 0xfa, 0xff,
	0x13, 0x8c, 0x4d, 0xd2, 0x02, 0xf0, 0xf8, 0x74, 0x3a, 0x16, 0x1f, 0xdd, 0x28, 0x6e, 0x88, 0xe5,
	0xa1, 0xaf, 0x61, 0xeb, 0x52, 0x56, 0x3d, 0x8a, 0xf2, 0x3a, 0xa1, 0x9a, 0x7a, 0x3b, 0xa7, 0x5f,
	0x61, 0xea, 0x9b, 0x7e, 0x86, 0x6d, 0x93, 0x3d, 0xaf, 0x48, 0x96, 0xe2, 0xcf, 0xa6, 0xd2, 0xa5,
	0xf2, 0x2b, 0x2c, 0x36, 0x49, 0x0b, 0xca, 0x21, 0x8e, 0x1a, 0xa5, 0x76, 0xb9, 0xb3, 0x7e, 0xba,
	0x71, 0x1c, 0x8b, 0x8c, 0xe1, 0x88, 0xc9, 0x00, 0x1d, 0xc2, 0xce, 0x4d, 0x30, 0x74, 0x05, 0x4a,
	0x4f, 0x4e, 0x31, 0x16, 0xe1, 0xd2, 0x43, 0x84, 0xcb, 0x09, 0xc2, 0x35, 0x78, 0x64, 0xdd, 0xa2,
	0xdb, 0xf8, 0x1c, 0x88, 0x35, 0xb8, 0xbc, 0x99, 0xd4, 0xa1, 0xb6, 0x70, 0x7a, 0x0e, 0x72, 0xfa,
	0x77, 0x05, 0xaa, 0xd7, 0x7c, 0x88, 0xac, 0x77, 0x4e, 0x3e, 0xc1, 0xba, 0x25, 0x7c, 0xd2, 0x34,
	0x6c, 0x93, 0x0b, 0xc4, 0x39, 0x48, 0x0f, 0xea, 0xd2, 0x0a, 0xe4, 0x0a, 0xd6, 0x8c, 0xca, 0xc9,
	0x63, 0x73, 0x78, 0x79, 0x83, 0x38, 0xed, 0xb4, 0x90, 0xad, 0x17, 0x5a, 0x38, 0x29, 0x92, 0x3e,
	0x6c, 0x2d, 0x6a, 0x9a, 0xb4, 0xac, 0x51, 0xa4, 0x6c, 0x07, 0xe7, 0x49, 0x66, 0xdc, 0x94, 0xd8,
	0x87, 0xad, 0x45, 0x65, 0x5b, 0xa0, 0xa9, 0x7b, 0xc2, 0x02, 0xcd, 0x58, 0x09, 0x05, 0xf2, 0x1d,
	0x36, 0x17, 0xc4, 0x4f, 0x0e, 0x6d, 0x82, 0x89, 0x65, 0xe1, 0x1c, 0x65, 0x85, 0x13, 0x3d, 0x40,
	0xd8, 0x4d, 0x93, 0x2a, 0x39, 0xb2, 0x27, 0x91, 0xb5, 0x2a, 0x9c, 0x67, 0x39, 0xa7, 0x0c, 0x81,
	0x01, 0xd4, 0x52, 0xb4, 0x4b, 0x9e, 0x9a, 0xfc, 0xec, 0x7d, 0x60, 0x91, 0x79, 0x48, 0xfe, 0x05,
	0xf2, 0x06, 0xaa, 0x5a, 0x81, 0x64, 0xdf, 0xe6, 0x6f, 0x29, 0xda, 0x69, 0x24, 0x03, 0x26, 0xff,
	0x02, 0xd6, 0x8c, 0x1c, 0xac, 0xc7, 0xb5, 0x2c, 0x44, 0xc7, 0x49, 0x0b, 0x19, 0x94, 0xaf, 0x52,
	0x3f, 0xea, 0xa0, 0xd5, 0x0f, 0xeb, 0xd5, 0x27, 0xc5, 0x65, 0xbd, 0xfa, 0x14, 0x2d, 0xd1, 0xc2,
	0xfb, 0xca, 0x8f, 0x52, 0x30, 0x18, 0xac, 0xa8, 0x5f, 0xf0, 0xd9, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0xf2, 0xeb, 0x45, 0x93, 0x07, 0x00, 0x00,
}
